### ISSUE TITLE
C extension does not compile on py3.9 without re-cythonizing

### ISSUE THREAD

**Issue by danieldjewell** [pytroll/python-geotiepoints#29]
Building master fails on cpython 3.9.1:

```
geotiepoints/multilinear_cython.c:24742:26: error: no member named 'tp_print' in
'struct _typeobject'
__pyx_type___pyx_array.tp_print = 0;
~~~~~~~~~~~~~~~~~~~~~~ ^
geotiepoints/multilinear_cython.c:24747:32: error: no member named 'tp_print' in
'struct _typeobject'
__pyx_type___pyx_MemviewEnum.tp_print = 0;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
geotiepoints/multilinear_cython.c:24762:31: error: no member named 'tp_print' in
'struct _typeobject'
__pyx_type___pyx_memoryview.tp_print = 0;
~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
geotiepoints/multilinear_cython.c:24775:36: error: no member named 'tp_print' in
'struct _typeobject'
__pyx_type___pyx_memoryviewslice.tp_print = 0;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^

```

Removing ```geotiepoints/multilinear_cython.c``` and running ```cythonize -3 multilinear_cython.pyx``` appears to fix the issue .... (Cython 0.29.21)

I saw #4 and while on one hand pre-generating the C source does make it possible to install w/o Cython, I'm not sure that Cython was designed around that idea?

**Comment by djhoese** [comment]
Thanks for pointing this out. While I have always liked the idea of bundling the rendered C/C++ it has definitely caused more problems in the last couple years for the few packages pytroll uses cython in. I'd be OK with always re-rendering and including cython as a build requirement.
