### PR TITLE
Switch build system to require Cython and build extensions on install

### LINKED ISSUE #27: MNT: Stop using ci-helpers in appveyor.yml
To whom it may concern,

If you are using https://github.com/astropy/ci-helpers in your appveyor.yml , please know that the Astropy project has dropped active development/support for Appveyor CI. If it still works, good for you, because we did not remove the relevant files (yet). But if it ever stops working, we have no plans to fix anything for Appveyor CI. Please consider using native Windows support other CI, e.g., Travis CI (see https://docs.travis-ci.com/user/reference/windows/). We apologize for any inconvenience caused.

If this issue is opened in error or irrelevant to you, feel free to close. Thank you.

xref astropy/ci-helpers#464

### LINKED ISSUE #29: C extension does not compile on py3.9 without re-cythonizing
Building master fails on cpython 3.9.1:

```
geotiepoints/multilinear_cython.c:24742:26: error: no member named 'tp_print' in
'struct _typeobject'
__pyx_type___pyx_array.tp_print = 0;
~~~~~~~~~~~~~~~~~~~~~~ ^
geotiepoints/multilinear_cython.c:24747:32: error: no member named 'tp_print' in
'struct _typeobject'
__pyx_type___pyx_MemviewEnum.tp_print = 0;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
geotiepoints/multilinear_cython.c:24762:31: error: no member named 'tp_print' in
'struct _typeobject'
__pyx_type___pyx_memoryview.tp_print = 0;
~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
geotiepoints/multilinear_cython.c:24775:36: error: no member named 'tp_print' in
'struct _typeobject'
__pyx_type___pyx_memoryviewslice.tp_print = 0;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^

```

Removing ```geotiepoints/multilinear_cython.c``` and running ```cythonize -3 multilinear_cython.pyx``` appears to fix the issue .... (Cython 0.29.21)

I saw #4 and while on one hand pre-generating the C source does make it possible to install w/o Cython, I'm not sure that Cython was designed around that idea?

### PR DESCRIPTION
**Pull request by djhoese**
This PR rewrites a lot of the old "cruft" of this package.

1. Instead of compiling the Cython extensions into C at package time it is now done on installation. This will save us from being incompatible as newer versions of Python come out and change the API.
2. Switch to GitHub actions for testing and deployment
3. Update installation instructions to use pip and conda.

 - [x] Closes #27 
 - [x] Closes #29
 - [x] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``git diff origin/master **/*py | flake8 --diff`` 
 - [x] Fully documented

### CODE REVIEW

**Comment by djhoese** [comment]
Tests pass: https://github.com/djhoese/python-geotiepoints/actions/runs/629918606

I'll see if I can test deployment shortly.

**Comment by djhoese** [comment]
Something weird is going on in the Python 3.9 deploy jobs. The OSX and Windows builds on Python 3.9 are failing because the Cython file isn't being compiled and it is somehow getting access to the old Cython file. However:

1. The `.c` file is no longer in the repository (in this PR).
2. The "USE_CYTHON" environment variable being mentioned in the logs is also not part of this PR anymore.

It seems GitHub is pulling an old version or merging them in an odd way. Latest run: https://github.com/djhoese/python-geotiepoints/actions/runs/630162203

**Comment by djhoese** [comment]
Everything except those builds pass. @mraspaud I'd say if you're OK with the rest of this we merge it, make a tag, watch the PyPI test upload (which should go on tags), and then make the github release is everything works. Otherwise, I do more debugging.

**Comment by djhoese** [comment]
Ah I think I know the problem. The github action is using the merge of master and my branch. Since I deleted the file in my branch, but it still exists in master, it must be taking the file from master which is causing `cythonize` not to run...maybe.

**Review by mraspaud — APPROVED** [review]
LGTM, thanks for adding the actions at the same time!

**Comment by mraspaud** [comment]
I'm merging this, we will see what the actions say.

**Comment by mraspaud** [comment]
This worked, so tagging now.

**Comment by mraspaud** [comment]
something went wrong with the test-pypi upload, so waiting for the actual release:
https://github.com/pytroll/python-geotiepoints/actions/runs/631905324

**Comment by djhoese** [comment]
Looks like the test PyPI token...oh! My token on the test pypi that is in the pytroll organization is probably only for pyresample. Let me try updating or adding another one. Also:

```
 Checking dist/python_geotiepoints-1.2.1-cp37-cp37m-win_amd64.whl: PASSED, with warnings
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
  warning: `long_description` missing.
```

**Comment by djhoese** [comment]
Updated API token for the test PyPI and restarted jobs.

**Comment by djhoese** [comment]
Success! https://github.com/pytroll/python-geotiepoints/runs/2056548321?check_suite_focus=true

**Comment by djhoese** [comment]
https://test.pypi.org/project/python-geotiepoints/

**Comment by mraspaud** [comment]
perfect! Releasing now.
